[package]
name = "eufy-cheater-code"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.10.3"
futures = "0.3.25"
tokio = { version="1.21.2", features=["full"]}
uuid = "1.2.1"
